#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/teamdesk/teamdesk /usr/bin/teamdesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/teamdesk.service ]; then
			rm /etc/systemd/system/teamdesk.service /usr/lib/systemd/system/teamdesk.service /usr/lib/systemd/user/teamdesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/teamdesk/files/systemd/teamdesk.service /usr/lib/systemd/system/teamdesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload teamdesk.service: Unit teamdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/teamdesk.service:10: Executable path is not absolute: pkill -f "teamdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/teamdesk.service
		fi
		systemctl daemon-reload
		systemctl enable teamdesk
		systemctl start teamdesk
	fi
fi
