name: Teamdesk build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      upload-artifact:
        description: "Upload artifacts / publish release"
        type: boolean
        default: true
jobs:
  build:
    permissions:
      contents: write
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
      upload-tag: "teamdesk-nightly"
    secrets: inherit
